name: CI

on:
  pull_request: ~

  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run:
          npx turbo run lint:eslint lint:types lint:md lint:knip
          lint:package-json lint:spelling lint:prettier test
